# Generated by Django 5.2.17 on 2026-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='census_day',
            field=models.DateField(blank=True, help_text='Reference/enumeration day the dashboard countdown counts down to.', null=True),
        ),
    ]
