# Generated by Django 5.2.17 on 2026-09-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_census_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workstream',
            name='backup_lead',
            field=models.ForeignKey(blank=True, help_text='Stands in for the Lead -- included on workstream alerts and used as a fallback recipient when an activity has no individually-assigned owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_led_workstreams', to=settings.AUTH_USER_MODEL),
        ),
    ]
