# Generated by Django 5.2.17 on 2026-09-03 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workstream_backup_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='co_owner',
            field=models.ForeignKey(blank=True, help_text='Second Project Owner with the same authority and alerts as the primary owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_owned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
