# Generated by Django 5.2.17 on 2026-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_sms_notifications',
            field=models.BooleanField(default=False, help_text='Turn on to also receive urgent (overdue/at-risk) alerts by SMS, in addition to email. Requires a phone number on file; standard message rates apply.'),
        ),
    ]
