# Generated by Django 5.2.17 on 2026-09-02 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Milestone / Activity')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('dependency', models.TextField(blank=True, verbose_name='Dependency / Input')),
                ('deliverable', models.TextField(blank=True, verbose_name='Deliverable / Expected Output')),
                ('responsible_text', models.CharField(blank=True, help_text="Raw name/team from the workbook, kept even when it doesn't match a system user.", max_length=300, verbose_name='Responsible Person / Team Contact')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('AT_RISK', 'At Risk')], default='NOT_STARTED', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('phase', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('is_milestone', models.BooleanField(default=False, help_text='Flags this as a major milestone for completion alerts.')),
                ('source_row_key', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('responsible', models.ForeignKey(blank=True, help_text='Matched system user, if the uploaded name matched one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_activities', to=settings.AUTH_USER_MODEL)),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.workstream')),
            ],
            options={
                'ordering': ['end_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual edit'), ('UPLOAD', 'Workbook upload')], default='MANUAL', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='activities.activity')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'workstream', 'status'], name='activities__project_02897d_idx'),
        ),
    ]
