# Generated by Django 5.2.17 on 2026-09-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Workstream Owner (or above) who validated this as Completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('PENDING_VALIDATION', 'Pending Validation'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('AT_RISK', 'At Risk')], default='NOT_STARTED', max_length=20),
        ),
    ]
