# Generated by Django 5.2.17 on 2026-09-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline reminder'), ('OVERDUE', 'Activity overdue'), ('AT_RISK', 'Activity marked at risk'), ('STATUS_CHANGE', 'Activity status changed'), ('TASK_ASSIGNED', 'Task assigned to owner'), ('MILESTONE_COMPLETED', 'Major milestone completed'), ('WORKSTREAM_OVERDUE', 'Workstream has several overdue activities'), ('WEEKLY_DIGEST', 'Weekly summary digest')], max_length=30)),
                ('days_before', models.PositiveSmallIntegerField(blank=True, help_text='Used by Deadline reminder: days before the end date to alert.', null=True)),
                ('threshold', models.PositiveSmallIntegerField(blank=True, help_text='Used by Workstream overdue: number of overdue activities that triggers an alert.', null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rule_type', 'days_before'],
                'constraints': [models.UniqueConstraint(fields=('rule_type', 'days_before'), name='unique_rule_type_days_before')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline reminder'), ('OVERDUE', 'Activity overdue'), ('AT_RISK', 'Activity marked at risk'), ('STATUS_CHANGE', 'Activity status changed'), ('TASK_ASSIGNED', 'Task assigned to owner'), ('MILESTONE_COMPLETED', 'Major milestone completed'), ('WORKSTREAM_OVERDUE', 'Workstream has several overdue activities'), ('WEEKLY_DIGEST', 'Weekly summary digest')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='activities.activity')),
                ('workstream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.workstream')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['rule_type', 'activity', 'sent_at'], name='notificatio_rule_ty_194e3f_idx')],
            },
        ),
    ]
