# Generated by Django 5.2.17 on 2026-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_rule_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='rule_type',
            field=models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline reminder'), ('OVERDUE', 'Activity overdue'), ('AT_RISK', 'Activity marked at risk'), ('STATUS_CHANGE', 'Activity status changed'), ('TASK_ASSIGNED', 'Task assigned to owner'), ('MILESTONE_COMPLETED', 'Major milestone completed'), ('WORKSTREAM_OVERDUE', 'Workstream has several overdue activities'), ('WEEKLY_DIGEST', 'Weekly summary digest'), ('VALIDATION_REQUESTED', 'Activity ready for validation'), ('COMPLETION_VALIDATED', 'Completion validated by workstream owner'), ('MANUAL_ALERT', 'Manually triggered workstream alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='rule_type',
            field=models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline reminder'), ('OVERDUE', 'Activity overdue'), ('AT_RISK', 'Activity marked at risk'), ('STATUS_CHANGE', 'Activity status changed'), ('TASK_ASSIGNED', 'Task assigned to owner'), ('MILESTONE_COMPLETED', 'Major milestone completed'), ('WORKSTREAM_OVERDUE', 'Workstream has several overdue activities'), ('WEEKLY_DIGEST', 'Weekly summary digest'), ('VALIDATION_REQUESTED', 'Activity ready for validation'), ('COMPLETION_VALIDATED', 'Completion validated by workstream owner'), ('MANUAL_ALERT', 'Manually triggered workstream alert')], max_length=30),
        ),
    ]
